"""empty message

Revision ID: 7280d47b3c5e
Revises: 
Create Date: 2022-07-30 12:36:46.875716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7280d47b3c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('five_pokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poke1_name', sa.String(length=50), nullable=True),
    sa.Column('poke2_name', sa.String(length=50), nullable=True),
    sa.Column('poke3_name', sa.String(length=50), nullable=True),
    sa.Column('poke4_name', sa.String(length=50), nullable=True),
    sa.Column('poke5_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('five_pokes')
    op.drop_table('user')
    # ### end Alembic commands ###
